export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const SELECT_PHYSICIAN = "SELECT_PHYSICIAN";
export const GET_PHYSICIANS = "GET_PHYSICIANS";
export const PHYSICIAN_ERROR = "PHYSICIAN_ERROR";
export const GET_APPOINTMENTS = "GET_APPOINTMENTS";
export const APPOINTMENT_ERROR = "APPOINTMENT_ERROR";
